#Build multi-arch image with buildx
name: build multi-arch image
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     platform:
    #     - linux/amd64
    #     - linux/arm/v7
    #     - linux/arm64
    env:
      REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      REGISTRY_ALIAS: ${{ secrets.ECR_PUBLIC_REPO_ALIAS }}
      REPOSITORY: ${{ secrets.REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_GITHUB_ACTIONS }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build, tag, and push multi-arch image to AWS ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm/v7, linux/arm64
          push: true
          tags: $REGISTRY/$REPOSITORY:$IMAGE_TAG

